[project]
name = "leetcode-solutions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.12.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.0",
]
