name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Run Ruff Lint and Format
        run: |
          # Run ruff check with --fix and --unsafe-fixes
          uv run ruff check --fix --unsafe-fixes
          # Run ruff format
          uv run ruff format

      - name: Auto-commit ruff changes
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            echo "Files were modified by ruff. Committing fixes directly to current branch..."
            
            # Add and commit changes directly to current branch
            git add .
            git commit -m "Auto-fix: Apply ruff check --fix and ruff format" \
                       -m "This commit contains automatic fixes applied by:" \
                       -m "- uv run ruff check --fix" \
                       -m "- uv run ruff format" \
                       -m "" \
                       -m "Generated by GitHub Actions on $(date)"
            
            # Push directly to the current branch
            git push origin HEAD
            
            echo "✅ Committed ruff fixes directly to branch: ${GITHUB_REF#refs/heads/}"
          else
            echo "✅ No files were modified by ruff."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_LINGC2001 }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest
