name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: uv sync
      - name: Run Ruff (check and fix)
        run: uv run ruff check --fix
      - name: Run Ruff (format)
        run: uv run ruff format
      - name: Auto-commit ruff changes
        if: github.event_name == 'push'
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            echo "Files were modified by ruff. Creating PR with fixes..."
            
            # Create a new branch
            BRANCH_NAME="ruff-fixes-$(date +%s)"
            git checkout -b "$BRANCH_NAME"
            
            # Add and commit changes
            git add .
            git commit -m "Auto-fix: Apply ruff check --fix and ruff format" \
                       -m "This commit contains automatic fixes applied by:" \
                       -m "- uv run ruff check --fix" \
                       -m "- uv run ruff format" \
                       -m "" \
                       -m "Generated by GitHub Actions on $(date)"
            
            # Push the branch
            git push origin "$BRANCH_NAME"
            
            # Create pull request using GitHub CLI
            gh pr create \
              --title "🔧 Auto-fix: Ruff formatting and linting fixes" \
              --body "This PR contains automatic fixes applied by Ruff:

            ## Changes made:
            - Applied \`uv run ruff check --fix\` to fix auto-fixable linting issues
            - Applied \`uv run ruff format\` to format code according to project standards

            ## Files modified:
            \`\`\`
            $(git diff --name-only HEAD~1)
            \`\`\`

            This PR was automatically created by the CI workflow. Please review the changes and merge if they look correct.

            **Generated by GitHub Actions** 🤖" \
              --head "$BRANCH_NAME" \
              --base "main"
            
            echo "✅ Created pull request for ruff fixes on branch: $BRANCH_NAME"
          else
            echo "✅ No files were modified by ruff."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for uncommitted changes (PR only)
        if: github.event_name == 'pull_request'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ Files were modified by ruff. Please run the following commands locally and commit the changes:"
            echo ""
            echo "uv run ruff check --fix"
            echo "uv run ruff format"
            echo ""
            echo "Modified files:"
            git status --porcelain
            echo ""
            echo "Diff:"
            git diff
            exit 1
          else
            echo "✅ No files were modified by ruff."
          fi
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest
