name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-goalie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: uv sync
      - name: Install Goalie
        run: uv tool install git+https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/zzl0626/repo-goalie
      - name: Run Goalie
        run: goalie greet -n ${{ github.actor }}
